refining linter CI

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -16,10 +16,26 @@ jobs:
       - uses: actions/setup-node@v4
         with:
           node-version: 18
-      - name: install
+      - name: install moonbit runtime
         run: |
-          /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.cn/install/unix.sh)"
+          /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/install/unix.sh)"
           echo "$HOME/.moon/bin" >> $GITHUB_PATH
           npm install -g @moonbit/markdown-linter
-      - name: lint
-        run: find . -name '*.md' | while read file; do echo "========in $file, mdlint yields========"; mdlint "$file"; done
+      - name: lint markdowns
+        run: |
+          FAIL=0
+          FAILED_FILES=()
+          find . -name '*.md' | while read file; do
+            echo "========mdlint results for $file========";
+            mdlint "$file" || {
+              FAIL=1
+              FAILED_FILES+=("$file")
+            }
+          done
+          for file in "${FAILED_FILES[@]}"; do
+            echo "========mdlint failed for $file========"
+          done
+          if [[ $FAIL -eq 1 ]]; then 
+            echo "::error file=${FAILED_FILES}::Markdown lint failed"; 
+            exit 1; 
+          fi
